### PR TITLE
Configurable property to update with track

### PR DESCRIPTION
**Pull request by nagyrobi**
to be able to update not just "val" but anything else

### CODE REVIEW

**Comment by nagyrobi** [comment]
For https://github.com/dgomes/hasp-lvgl-custom-component/issues/7

**Comment by dgomes** [comment]
Thanks for this PR :)

I was actually planning in having the possibility to link entities to various properties:

```
      - obj: "p1b3" #This is a checkbox
        text: {{ state_attr('automation.rise_and_shine', 'friendly_name') }}
        val: {{ state('automation.rise_and_shine') }}

**Comment by dgomes** [comment]
Highly appreciated! :)

**Comment by nagyrobi** [comment]
I would give it a shot if you'd point me into the right direction on how to expand the template into a result variable.

**Comment by dgomes** [comment]
It's all handled by TemplatEntity https://github.com/home-assistant/core/blob/6fb2e63e49f01d9eaf09c7b21122981e462e4e99/homeassistant/components/template/template_entity.py

I always find it easier to look into existing components that already support the feature I want to implement and learn from their implementations.

**Comment by dgomes** [comment]
Major refactor yesterday, please have a look

**Comment by nagyrobi** [comment]
Nice, I see the `# TODO support more then "val"` at `async_listen_state_changes`.
Wonder if I add the template to variable resolver above in __init__ would that be enough or should it be pushed down in async_listen_state_changes to receive updates regularly?

**Comment by dgomes** [comment]
I'm afraid that will not be enough, tonight I might have some extra time to try and address this

**Comment by nagyrobi** [comment]
I think to add a configurable, optional `factor` parameter to the `obj` section which would be useful to address [this](https://github.com/fvanroie/hasp-lvgl/issues/81). 
The **arc** in hasp-lvgl can only handle integers, so you need to set it to move between 150 and 300, and divide by factor 10 to obtain decimal values to set a target temperature in Home Assistant. 
- But you need to multiply back with 10 when you update the `val` of the **arc**. 
- And you need not to multiply with anything when updating other properties like `value_str`.
So  `factor` parameter would be only involved in reading (divison) and setting (multiplication) of the `val` property.

**Comment by dgomes** [comment]
a1f5704fc1a71e0e6188f796e5e2b34e98c190c4 implements this

**Comment by dgomes** [comment]
you can type any conversion you wish into the template to set the hasp objective property, now I'll work on the event side

**Comment by dgomes** [comment]
Done in 4795760dfd1e100e0350102a4b5f9c19671cb87c
event service call can now use variables (MQTT messages key/values) in their service templates

**Comment by nagyrobi** [comment]
> event service call can now use variables (MQTT messages key/values) in their service templates

What's the syntax? For MQTT message sent by the plate: `{"event":"changed","val":110}` how do I extract the val?

To achieve something like this:
```yaml
        event:
          "changed":
            service: climate.set_temperature
            data_template:
              entity_id: climate.futes
              temperature: "{{ val / 10 }}"
```

**Comment by dgomes** [comment]
`              temperature: "{{ val | int / 10 }}"
`

**Comment by dgomes** [comment]
also you don't need "data_template" it's just "data"... you can test the service call in developer-tools/server and then copy & paste to the configuration.yaml

**Comment by nagyrobi** [comment]
Excellent. 
try:
`{"obj":"arc","id":3,"x":20,"y":75,"w":200,"h":200,"min":120,"max":460,"border_side":0,"type":0,"rotation":0,"start_angle":135,"end_angle":45,"start_angle1":135,"end_angle1":45,"value_font":28,"value_color":"#2C3E50","adjustable":"true"}`

and 

```
      - obj: "p2b3"
        properties:
          "val": "{{ state_attr('climate.climate1','temperature') * 10 | int }}" 
          "value_str": "{{ state_attr('climate.climate1','temperature') }}" 
        event:
          "changed":
            service: climate.set_temperature
            data:
              entity_id: climate.climate1
              temperature: "{{ val | int / 10 }}"
```

**Comment by dgomes** [comment]
does it work or not ?

You should join the hasp-lvgl discord ;)

**Comment by nagyrobi** [comment]
it works but it needs some throttling

**Comment by dgomes** [comment]
can't do much from HA side... if the events are generated, they are being processed

**Comment by nagyrobi** [comment]
There's a race causing this:
https://user-images.githubusercontent.com/1550668/112021864-05640a00-8b32-11eb-80f0-20a17051770c.mp4

I think what happens is:
- I drag the arc, object changed
- plate sends an MQTT
- HA gets it as event -> component adjusts the entity
- entity has changed -> component sends MQTT
- plate gets it as update command -> adjusts the arc, object changed
- and goto line 1 again....

**Pull request closed without merging**
