### PR TITLE
race handling

### PR DESCRIPTION
**Pull request by nagyrobi**
A basic attempt to avoid race condition https://github.com/dgomes/hasp-lvgl-custom-component/pull/14#issuecomment-804202017

### CODE REVIEW

**Review by dgomes — COMMENTED** [review]
We should not code in an edge case for "val", it would be better to solve this in the firmware.

just curious, does this work for you ?

**Comment by nagyrobi** [comment]
It works 90% of the cases. If I drag too fast, 10% cases still jumps. I guess it's a timing issue.
I think it can safely be hardcoded to `val` as that's the only existing case which could ever cause this. You're setting back the same val that triggered the change.

**Comment by nagyrobi** [comment]
Not needed anymore because https://github.com/fvanroie/hasp-lvgl/pull/111 lets us use up events.

**Comment by htvekov** [comment]
To avoid this race condition, I use a >1 second timestamp condition evaluating when HA volume sensor value should be pushed to all plates.

Has been working as expected here for weeks until my plates recently decided to go 'belly up'... ☠🙄 

```yaml
- id: hasp_sonos_volume - push
  alias: hasp_sonos_volume - push
  mode: restart
  trigger:
    platform: state
    entity_id: sensor.volume
  condition:
    condition: template
    value_template: '{{ now().timestamp() - as_timestamp(states.sensor.hasp_volume.last_changed)
      > 1 }}'
  action:
  - service: mqtt.publish
    data:
      topic: hasp/plates/command/p2b20.val
      payload_template: '{{ trigger.to_state.state }}'
  - service: mqtt.publish
    data:
      topic: hasp/plates/command/p2b20.value_str
      payload_template: '{{ trigger.to_state.state }}'
```

**Comment by nagyrobi** [comment]
Ok but the goal is to handle such things within the component.

**Comment by htvekov** [comment]
Could you save timestamp for arc/slider up events in cc ? Then you could do time compare against this to decide if HA value should be pushed to plate or not.

**Comment by dgomes** [comment]
that's the throttle I'm mentioning... but it will also make things less "snappy"

**Comment by htvekov** [comment]
If you only throttle arc/slider values pushed TO plates, I guess no one will be complaining 🙂
All such direct HA sensor <--> arc/slider implementations would all start a unintentional race condition.

Can't think of a use case where you actually would wan't instant sync of value from HA to plate, as plate already has the value.
Or am I missing the obvious  exception ??? 😉

**Comment by dgomes** [comment]
I measure power consumption in the plate, I like to have my values in RT :)

**Comment by dgomes** [comment]
BTW I was thinking of throttling the other way around PLATE -> HA, from what I'm seeing that's where to many events are being generated

**Comment by htvekov** [comment]
@fvanroie already implemented mqtt message throttling some days ago 🙂
5 mqtt messages max. pr. second now
So no need to cut down on the flow from plate to HA.

**Comment by nagyrobi** [comment]
> @fvanroie already implemented mqtt message throttling some days ago

Yes that's very noticeable and it fixes the "elasticness" of the object during motion.
The problem is that:
- while you drag the handle, a change is sent with a value at an unknown moment in time
- you still keep dragging, but meanwhile a message is coming back from HA for the same object with the earlier val
- this causes a jump back of the handle from under your finger. which causes a change message again

We should simply block sending back "val" back to the same object and plate which originated it.

**Comment by nagyrobi** [comment]
Moreover: I see that change is useless to update other plates on the network. When I drag the volume slider of a media player in Home Assistant (that doesn't generate change events, the player just sends the val through the component when slider released) causes the slider in hasp-lvgl to move smoothly with animation.

So there's no need to stress plates with messages originating from "change" at all. Actually "change" messages should only be processed by HA for is own use, feedback changes to the plates in these cases could be blocked.

**Comment by nagyrobi** [comment]
Now with @fvanroie's throttling it's already very effective.

**Pull request closed without merging**
