### PR TITLE
Update services.yaml

### PR DESCRIPTION
**Pull request by nagyrobi**
Add _ character to clear_page service name to be consistent with all other service names
Improve service descriptions

### CODE REVIEW

**Review by dgomes — CHANGES_REQUESTED** [review]
If line 29 is changed, the service name must also be updated in consts.py

I kept clearpage from the firmware command (they don't have _)

**Comment by nagyrobi** [comment]
it is

**Comment by dgomes** [comment]
You must commit to the same branch...

You are using the web interface aren't you :) ?

**Review by dgomes — APPROVED** [review]

**Comment by nagyrobi** [comment]
> You are using the web interface aren't you :) ?

Yes, mostly.

**Pull request merged**
